### ISSUE TITLE
Minecraft Server

### ISSUE THREAD

**Issue by SuNG0D** [virus-rpi/SpaceInvader#1]
Hello, i'm SuNG0D.

It appears that you and your friend have logged into my Minecraft server. (It's not french btw, it's catalan)

Would like to talk to you about it and try to know how you were able to acces it. (for example, how did you find the Server IP in the first place) Also, I would like to know if you did something to the server, did you explode anything, did you steal anything?

I'll wait for a response patiently.

Regards.

SuNG0D

**Comment by noa-santo** [comment]
Hello SuNG0D,
I indeed logged onto your server.

I have found it through a tool called Qubo Scanner. With this tool I just pinged all IP addresses and checked if they have port 25565 open. This scanner found 425 servers, which I connected with my friend SatsumaCLP999.

So I can't tell you if we did something on your server, because I don't know exactly which one is yours.

For the future I would recommend that you whitelist the servers.


Regards.

virus_rpi

**Comment by SuNG0D** [comment]
My server IP is: *************

You placed an enderman, a grass block and a sign that said "i don't speak frensh". You also got the diamonds achievement and your friend kept getting kicked by the server for flying (or that's what the console log says). You connected yesterday around 14:30 maybe?

Also, when I detected that someone entered the server without permission I whitelisted the server and IP-Banned you and your friend (since I don't know you and at first place I got scared thinking there was a security breach on my server or smthing).

And I've found it really easy to find information about you and to contact you, crazy how easy it is on the internet to find info, right?

Regards.

SuNG0D

PD: If you want to keep in contact, add me on Discord: SuNG0D#4350  :-)

**Comment by noa-santo** [comment]
I don't think we have done anything else on the server. 

Also, you should not post your IP publicly.

**Comment by X19S** [comment]
Speaking of posting IPs public, you as the repository owner also shouldn't upload IPs. 

Can you delete the text documents with the IPs?

**Comment by noa-santo** [comment]
Yes.
Thank you for reminding me.
